### ISSUE TITLE
comtypes on pypi has bad version info?

### ISSUE THREAD

**Issue by rkhwaja** [enthought/comtypes#111]
I'm not sure what the problem is but pip list --outdated is always returning something for comtypes. It claims that 1.1.3 is installed but 1.1.3.post2 is available.
If you pip install --upgrade comtypes, it downloads comtypes-1.1.3-2.zip.

**Comment by cfarrow** [comment]
I had to upload multiple archives to put out the release, hence `comtypes-1.1.3-2.zip`. I did not intend there to be a `post2` release, despite the name of zip archive. I'm surprised that pypi looks to the archive name instead of the metadata. (I'll have to read up on how all that works.)
