### ISSUE TITLE
how to pass a null parameter Autocad

### ISSUE THREAD

**Issue by YU6326** [enthought/comtypes#133]
Here is a vba example in autocad,
```vb
returnPnt = ThisDrawing.Utility.GetPoint(, "Enter a point: ")
```
the first parameter is optional.
so how to pass the first parameter to the function via python comtypes?

**Comment by junkmd** [comment]
@YU6326 

> so how to pass the first parameter to the function via python comtypes?

I am not familiar with the specification or implementation of the AutoCAD COM API, but I can say something in terms of my knowledge of `comtypes`.
The default value specified in `paramspec`(what you can figure out from the `COMMETHOD` and `DISPMETHOD` arguments), `None` or `automation.VARIANT.missing`.

If the issue remains, please re-open.
