### ISSUE TITLE
errors occured when convert from Word to PDF

### ISSUE THREAD

**Issue by robinshion** [enthought/comtypes#142]
It is work on my laptop but not work on my office desktop both of them using word 2007

please help

code is : 

```
docxfilepath = os.path.join(CURRENT_DIR,filename)

doc.save(docxfilepath)

wdFormatPDF = 17

word = comtypes.client.CreateObject('Word.Application')
doc = word.Documents.Open(docxfilepath)
doc.SaveAs(PDFfilepath, FileFormat=wdFormatPDF)
doc.Close()
word.Quit()
```

> File "C:\Db\test.py", line 1812, in <module>
>     doc.SaveAs(PDFfilepath, FileFormat=wdFormatPDF)
> _ctypes.COMError: (-2146824090, None, (u'Command failed', u'Microsoft Word', u'C
> :\\Program Files (x86)\\Microsoft Office\\Office12\\1033\\WDMAIN11.CHM', 36966,
> None))

**Comment by vasily-v-ryabov** [comment]
It doesn't work on older MS Office versions. Just no `Quit` method. Not a comtypes problem.
The same happens with `win32com.client` from pyWin32.

**Comment by robinshion** [comment]
THANKS

**Comment by yuen26** [comment]
@vasily-v-ryabov Thanks you. I also encounter the same error with MS Office 2007. But I don't know MS Office versions which this code will working with?

**Comment by rayoriz** [comment]
> Finally, I solved this problem. With MS Office 2007, please download and install this add-in: https://www.microsoft.com/en-us/download/details.aspx?id=7

Hello @yuen26 Can you please tell which add in you installed to resolve this issue? I am facing the same error and this addin is not available for download anymore.

**Comment by yuen26** [comment]
@rayoriz Sorry, I really don't remember this add-in. Please try installing [Microsoft Office Language Pack 2007 Service Pack 1 (SP1)](https://www.microsoft.com/en-us/download/details.aspx?id=14813).

**Comment by yuen26** [comment]
> > Finally, I solved this problem. With MS Office 2007, please download and install this add-in: https://www.microsoft.com/en-us/download/details.aspx?id=7
> 
> Hello @yuen26 Can you please tell which add in you installed to resolve this issue? I am facing the same error and this addin is not available for download anymore.

Hey @rayoriz , I found it. It's Microsoft Save as PDF or XPS add-in.
Reference (please Google translate to your language): [https://quantrimang.com/cach-don-gian-de-chuyen-file-excel-sang-pdf-118430](https://quantrimang.com/cach-don-gian-de-chuyen-file-excel-sang-pdf-118430)

**Comment by rayoriz** [comment]
@yuen26 : you are amazing buddy. Thanks a ton.

**Comment by XtremeGood** [comment]
I 'm getting this error despite being on Office 365 and windows 10 64 bit.

**Comment by junkmd** [comment]
@robinshion 
@vasily-v-ryabov 
@yuen26 
@rayoriz 

If the issue remains, please re-open.

**Comment by Dhaval-vegam** [comment]
i have converted to script to exe

while running this exe in cmd prompt its working fine but while adding this exe to service then its showing None type error 
i have defeined the proper path c:/path/to/dox and c:path/to/pdf

**Comment by alexrubis** [comment]
Encountered the same error with Word 2007 and yuen26 solution works like a charm. Thanks mate :)
