### ISSUE TITLE
error in comtypes 

### ISSUE THREAD

**Issue by Hari-Guhan-s** [enthought/comtypes#147]
("pRecInfo",POINTER(IUnknown))]
TypeError: _type_ must have storage info

**Comment by jonathanrocher** [comment]
@Hari-Guhan-s When reporting an issue on open source packages, you need to provide a LOT more information about your issue if you want a chance that someone will be able to help. What version of the package, how it was installed (source, pip, other), what platform, the simplest possible code snippet to reproduce the issue, and the full traceback.
