### ISSUE TITLE
Python-implemented COM servers broken with 64bit Python3

### ISSUE THREAD

**Issue by forderud** [enthought/comtypes#150]
Support for implementing COM servers in Python appears to be at least partly broken when running with 64bit Python 3.6. Minimal reproducer: https://github.com/forderud/public/tree/master/comtypes-64bit .

In this reproducer, `comtypes.client.CreateObject(...)`  fails when running with 64bit Python3.6. The problem is _not_ observed when running with either 32bit Python 2.7, 64bit Python 2.7 or 32bit Python 3.6.

The problem appears to be caused by passing of a memory address as `int`. This fails with a `int too long to convert` OverflowError when calling `CopyComPointer` in 64bit.
![image](https://user-images.githubusercontent.com/2671400/41206281-ea52f1be-6d01-11e8-80e8-cea743a74c59.png)

I suspect that the 2nd argument to `CopyComPointer` need to be changed from `int` to a more suitable type.

**Comment by forderud** [comment]
Gentle reminder. Can someone please confirm that this is a known issue? Any ideas for how to fix it?

**Comment by pekof** [comment]
I have similar issue.
My COM server is registered with 64bit python 3.7.1

When I use COM object from 32bit python client everything works fine.
Here is part of debug output from client where output from 32 and 64 differ:

> DEBUG:comtypes.client:CoCreateInstance({5555B182-3AB0-47D7-BDB3-ADE7D68A2937}, clsctx=None, interface=None)
DEBUG:comtypes.client:GetBestInterface(<POINTER(IUnknown) ptr=0xc293154 at c77c580>)

When i use COM object from 64bit python it fails differently depending on installed packages.
But in log first difference is:
> DEBUG:comtypes.client:CoCreateInstance({5555B182-3AB0-47D7-BDB3-ADE7D68A2937}, clsctx=None, interface=None)
DEBUG:comtypes.server.inprocserver:DllGetClassObject(clsid={5555B182-3AB0-47D7-BDB3-ADE7D68A2937}, iid={00000001-0000-0000-C000-000000000046})

Like it is trying to server from same process for some reason.

If I run it with python with all packages used in COM server then it fails like in this issue

> Traceback (most recent call last):
  File "C:\9tools\WPy-3710_64\python-3.7.1.amd64\lib\site-packages\comtypes\server\inprocserver.py", line 122, in DllGetClassObject
    result = ClassFactory(cls).IUnknown_QueryInterface(None, ctypes.pointer(iid), ppv)
  File "C:\9tools\WPy-3710_64\python-3.7.1.amd64\lib\site-packages\comtypes\_comobject.py", line 610, in IUnknown_QueryInterface
    return CopyComPointer(ptr, ppvObj)
OverflowError: int too long to convert

And if I run it with 64bit python which doesn't have some package installed it fails trying to load that package/module

>   File "C:\Users\HP\Work\ComServer\Foo.py", line 7, in <module>
    import SimpleITK as sitk
ModuleNotFoundError: No module named 'SimpleITK'

Where Foo.py is my registered COM server.
Foo.py should be run in separate process as is when used from 32bit python client.

**Comment by klusidy** [comment]
Hi, I've run into the same issue recently and was able to fix it by casting the parameter `ppv` to `ctypes.c_void_p` before calling `IUnkown_QueryInterface` (file `comtypes/server/inproceserver.py` function `DllGetClassObject()`)

I've created a pull request with the fix. I'm not 100% sure whether it is the correct place to do the conversion though.

**Comment by vasily-v-ryabov** [comment]
Hi @klusidy I could reproduce and verify the issue. Thanks for the fix! And thanks @forderud for the reproducer!
