### ISSUE TITLE
comtypes 1.1.5 installation (from pip) error on Python 3.6.4 x32 (Win7 x64)

### ISSUE THREAD

**Issue by sergey-scat** [enthought/comtypes#155]
pip install comtypes --upgrade

```
Running setup.py install for comtypes: started
  Running setup.py install for comtypes: finished with status 'error'
  Complete output from command c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-3mogtwij\\comtypes\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-88iag1pk-record\install-record.txt --single-version-externally-managed --compile:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option --single-version-externally-managed not recognized
```

**Comment by jwiggins** [comment]
This appears to be a pip/setuptools issue. What is the output when you run `pip --version`?

**Comment by sergey-scat** [comment]
Tried on pip 9.0.1 and 10.0.1 - the same error appears

"pip install comtypes==1.1.4" works fine on both

**Comment by jwiggins** [comment]
OK, thanks for the report; we'll look into it.

**Comment by vasily-v-ryabov** [comment]
I could reproduce it on my side as well. It produces the same error even with
```
pip install https://github.com/enthought/comtypes/releases/download/1.1.5/comtypes-1.1.5.zip
```
No ideas yet. I will have to debug it later today.

**Comment by vasily-v-ryabov** [comment]
`pip install --egg comtypes` magically helps, but with deprecation warning. The problem is in `setup.py`. Still bisecting the root cause...

**Comment by Loyoan** [comment]
win10 x64 python3.6.6  "pip install comtypes" failed.
"pip install comtypes==1.1.4" works .

**Comment by vasily-v-ryabov** [comment]
I'm done with the fix. Waiting 2 days for review and then posting 1.1.6.

**Comment by vasily-v-ryabov** [comment]
`comtypes==1.1.6` with the fix is out.

**Comment by Refene** [comment]
If this issue still happens, upgrade wheel first then try again with comtypes
python3 -mpip install --upgrade wheel
python3 -mpip install comtypes

**Comment by shukla1582** [comment]
pl help working on Virtual Hand Volume control using opencv on MacOs,while running the Pycaw it is showing error as below.

Traceback (most recent call last):
  File "/Users/akankshashukla/PycharmProjects/AI_Virtual_Mouse/VolumeHandControl.py", line 7, in <module>
    from comtypes import CLSCTX_ALL
  File "/Users/akankshashukla/PycharmProjects/AI_Virtual_Mouse/venv/lib/python3.7/site-packages/comtypes/__init__.py", line 375
    except COMError, err:
                   ^SyntaxError: invalid syntax


Process finished with exit code 1


does pycaw
<img width="546" alt="Screenshot 2022-01-14 at 2 24 05 AM" src="https://user-images.githubusercontent.com/90917353/149408279-c1b517f7-6baa-4caa-8435-4a61cd16c6cf.png">
 works with macOS, if not then what is the solution for below problem.

**Comment by vasily-v-ryabov** [comment]
Hi @shukla1582 AFAIK comtypes is Windows only. But this import error looks like comtypes was installed on Python2.7 first using `python setup.py install` and then comtypes is installed on Python 3.7 from the same local folder. Please uninstall comtypes from this virtual env and install it again from scratch (from clean downloaded folder). Not sure it would work on macOS (most probably not). But the import may work. If Pycaw doesn't use comtypes and it just imports it, maybe Pycaw will start working.
