### ISSUE TITLE
BUG: Compatibility with numpy 1.16.x 

### ISSUE THREAD

**Issue by pekof** [enthought/comtypes#178]
comtypes not working with numpy 1.16.x due to PR https://github.com/numpy/numpy/pull/12769

_automation.py_ and _safearray.py_ reference  `numpy.ctypeslib._typecodes` which is removed in that PR

**Comment by mobiusklein** [comment]
This appears to be solvable in a non-ideal fashion by replacing `numpy.ctypeslib._typecodes` with `numpy.ctypeslib._scalar_type_map`.

The optimal solution would be to build the mapping from `ctypes` type to `numpy.dtype` using the public API. Something along the lines of:

```python
import numpy as np
from numpy.ctypeslib import as_ctypes_type

ctypes_to_dtypes = {}

for tp in set(np.sctypeDict.values()):
    try:
        ctype_for = as_ctypes_type(tp)
        ctypes_to_dtypes[ctype_for] = tp
    except NotImplementedError:
        continue
```
This yields:
```python
{ctypes.c_long: numpy.int32,
 ctypes.c_ushort: numpy.uint16,
 ctypes.c_ulonglong: numpy.uint64,
 ctypes.c_longlong: numpy.int64,
 ctypes.c_ubyte: numpy.uint8,
 ctypes.c_byte: numpy.int8,
 ctypes.c_double: numpy.float64,
 ctypes.c_float: numpy.float32,
 ctypes.c_short: numpy.int16,
 ctypes.c_bool: numpy.bool_,
 ctypes.c_ulong: numpy.uint32}
```

Were there other types supported previously that are missing from this?

**Comment by fockez** [comment]
May I ask, when will this fix be merged?

**Comment by mobiusklein** [comment]
If there are no other types to add support for, I can write a short patch to add this behavior. At the time I posted this solution, I thought that the repository had been abandoned.

**Comment by fockez** [comment]
I thought too, but I can still see the new mergers although no new release for a long time.
The other problem is that there is no replacement.
