### ISSUE TITLE
Problem installing comtypes on Windows 10 Pro when running pip 19.3.1 

### ISSUE THREAD

**Issue by mwoodpatrick** [enthought/comtypes#196]
I'm getting the following error:

     error: error in setup script: command 'bdist_wininst' has no such option 'install_script'

when running

   pip install comtypes

using pip 19.3.1 on windows 10 Pro 10.0.19536 N/A Build 19536

**Comment by mwoodpatrick** [comment]
I was using the version of python from the MS App store when I install python from 

    https://www.python.org/downloads/release/python-381/

Then install works

**Comment by wkschwartz** [comment]
Duplicate #199
