### ISSUE TITLE
    stream.Open(path, SpeechLib.SSFMCreateForWrite) _ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by kurdishdevil** [enthought/comtypes#197]
Hi, please check this error i have posted on stackoverflow

https://stackoverflow.com/questions/59702279/comtypes-keeps-the-created-file-running

**Comment by junkmd** [comment]
@kurdishdevil 

Your stackoverflow page is not found.

If the issue remains, please re-open.
