### ISSUE TITLE
error in setup script: command 'bdist_wininst' has no such option 'install_script'

### ISSUE THREAD

**Issue by PhilippeH1967** [enthought/comtypes#199]
I have this error when trying pip install com types 
system windows 10 64
python :  3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44)

Error;
 error: error in setup script: command 'bdist_wininst' has no such option 'install_script'

**Comment by vasily-v-ryabov** [comment]
Could you please provide `pip freeze` output? `wheel` package version is the most interesting! Please check the `wheel` version before updating it!

**Comment by viratsrivastava** [comment]
> I have this error when trying pip install com types
> system windows 10 64
> python : 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44)
> 
> Error;
> error: error in setup script: command 'bdist_wininst' has no such option 'install_script'



> I have this error when trying pip install com types
> system windows 10 64
> python : 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44)
> 
> Error;
> error: error in setup script: command 'bdist_wininst' has no such option 'install_script'

same problem here

**Comment by vasily-v-ryabov** [comment]
@viratsrivastava can you try `pip install wheel` first?

**Comment by NIKHILMVS** [comment]
> Could you please provide `pip freeze` output? `wheel` package version is the most interesting! Please check the `wheel` version before updating it!
thank you so much I was trying this since 1 day
