### ISSUE TITLE
Module has no attribute problem.

### ISSUE THREAD

**Issue by fockez** [enthought/comtypes#200]
I use comtypes within anaconda under win10 64 to talk to ASCOM telescope driver, then I always met the error
 `module 'comtypes.gen.ASCOM_DeviceInterfaces' has no attribute 'ITelescopeV3'`
I follow the suggestion to clear the gen dir,  for the first time I met
 `item 1 in _argtypes_ passes a union by value, which is unsupported`
then the same.
The numpy version is 1.18.1, I want to use comtypes to get numpy array directly from camera driver, without safearray, win32com is too slow for this, I hope comtypes can help.

Thanks.

**Comment by fockez** [comment]
On an old computer, comtypes 1.1.4 and numpy 1.14.2, works fine.

**Comment by fockez** [comment]
Comfirm the python 3.7.6 cause the problem. Downgrade to 3.7.5 solves it.

**Comment by yinkaisheng** [comment]
#202  similar. 3.7.5 is ok.

**Comment by junkmd** [comment]
@fockez 
@yinkaisheng 

[This may be caused by a cpython problem](https://github.com/enthought/comtypes/issues/202#issuecomment-585866473).

If the issue remains, please re-open.
