### ISSUE TITLE
FileNotFoundError for GetModule with relative path

### ISSUE THREAD

**Issue by osrjv** [enthought/comtypes#222]
Hi,

The following snippet:
```
from comtypes.client import GetModule
GetModule('UIAutomationCore.dll')
```
Results in an error with the message `FileNotFoundError: [WinError 2] The system cannot find the file specified: 'UIAutomationCore.dll'` when run using comtypes `1.1.8`, however it works correctly when downgrading back to `1.1.7`.

The traceback points to this line: https://github.com/enthought/comtypes/blob/e5eeb5eac554531943f17f62815910fc1fd16017/comtypes/tools/codegenerator.py#L261

It seems like it's missing a check for the case where the filename is `None`, like is done earlier in the same function.

EDIT: It actually might not be `None`, but a file somewhere not in the current directory, as indicated by the documentation in GetModule()

**Comment by vasily-v-ryabov** [comment]
Hi @osrjv thanks for the report! To fix this problem we need to call function `_get_module_filename` from `client/_code_cache.py`. I'm currently thinking how to do it better as `codegenerator.py` is located in `tools` folder.

**Comment by vasily-v-ryabov** [comment]
Try the fix:
```
pip uninstall -y comtypes
pip install https://github.com/vasily-v-ryabov/comtypes/archive/fix_relative_path_load.zip
```

**Comment by nanonyme** [comment]
@vasily-v-ryabov tested on Windows on regular comtypes 1.1.8 importing pywinauto fails with UIAutomationCore.dll not found error, with above package it succeeds again. Are you planning to release with this soon?

**Comment by vasily-v-ryabov** [comment]
I'm trying to enable some unit tests, but it seems they need plenty of work. Probably I will release 1.1.9 with the current fix (it works with both .dll and .tlb files, but it's still risky).

**Comment by osrjv** [comment]
I also (finally) had a chance to test it out and the fix seems to work for my use-case. I think there might be some hidden bug still if the filename is `None` (the default value for the arg), but I'm not sure when that case is hit if ever.

**Comment by nanonyme** [comment]
@vasily-v-ryabov can you please either proceed with merge and release? Looks like various projects (well, we are too) are now excluding 1.1.8 as a broken version.

**Comment by vasily-v-ryabov** [comment]
`comtypes==1.1.9` is out.

**Comment by nanonyme** [comment]
@vasily-v-ryabov tested. This is still reproducing on Windows 7 with 1.1.9. on Windows 10 everything is working fine. Unclear yet what the difference is.

**Comment by nanonyme** [comment]
Essentially looks like variable full_filename is "UIAutomationCore.dll" instead of full path on Windows 7.

**Comment by vasily-v-ryabov** [comment]
Now fixed for Windows 7. Thanks @nanonyme for testing.
