### ISSUE TITLE
Pywinauto incompatible with comtypes ver 1.1.8

### ISSUE THREAD

**Issue by Avnsx** [enthought/comtypes#225]
Was working perfectly fine on the old version, just downgraded and it works again. Please fix!
Here's a stackoverflow thread regarding the topic: https://stackoverflow.com/questions/65459632/cannot-import-pywinauto-on-windows-10

**Comment by vasily-v-ryabov** [comment]
It should be fixed in `comtypes==1.1.9`. Please check. Sorry for long waiting.
