### ISSUE TITLE
Adapt to distutils being removed in 3.12

### ISSUE THREAD

**Issue by nanonyme** [enthought/comtypes#228]
Creating an issue about this for tracking. 3.10 release notes mark distutils as deprecated and set a date for removal https://docs.python.org/3.10/whatsnew/3.10.html#distutils

**Comment by nanonyme** [comment]
This links to https://github.com/enthought/comtypes/issues/216 in a way that it might or might not be harder to keep supporting Python 2 once distutils is gone.

**Comment by junkmd** [comment]
It would be good to work on this issue at the time of dropping Python 2.7 from support.

(related to #392)

**Comment by vasily-v-ryabov** [comment]
`1.2.1` uses `setuptools` and supports both Python 3.12 and still Python 2.7. I think the issue can be closed.
