### ISSUE TITLE
Create wheel package of comtypes

### ISSUE THREAD

**Issue by nanonyme** [enthought/comtypes#229]
Split from https://github.com/enthought/comtypes/issues/216

Currently new pip is forced to whenever installing this package to first locally create a wheel, then install it. We should be creating and publishing universal wheels. https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels

**Comment by junkmd** [comment]
This is related to #228.

I am thinking be started working on this after [Py3.11 first release](https://devguide.python.org/versions/#supported-versions).

## Assumed changes
https://github.com/enthought/comtypes/blob/cc9a0131edc76bd92073f75e9737aad40cd10c58/setup.py#L7-L11
↓
```py
from setuptools import Command, setup
from setuptools.command.install import install
from setuptools.command.build_py import build_py
```

**Comment by junkmd** [comment]
It would be good to work on this issue at the time of dropping Python 2.7 from support.

(related to #392)

**Comment by junkmd** [comment]
NOTE: this is related to #349.

**Comment by vasily-v-ryabov** [comment]
Current releases (including `1.2.1`, of course) have universal wheels already. Is this issue still relevant or should be closed?

**Comment by nanonyme** [comment]
You're right, this is done.

**Comment by junkmd** [comment]
I recognize a package as a universal wheel available package if it has a `.whl` file in the Built Distribution section of `https://pypi.org/project/NAME/#files`.

- For example, [`pyyaml`](https://pypi.org/project/PyYAML/#files), which is a green package at https://pythonwheels.com/, has Built Distributions, while [`pyspark`](https://pypi.org/project/PyYAML/#files), which is a white package [`pyspark`](https://pypi.org/project/pyspark/#files), which is a white package, does not have a Built Distribution.

https://pypi.org/project/comtypes/#files is satisfied the condition.

**Comment by nanonyme** [comment]
@junkmd it is not possible for projects with Python C extensions to have universal wheels. This includes pyyaml. That kind of projects have to build a per-platform wheel for all targets. Comtypes has no C extensions hence why it's possible here. Your definition for universal wheel is wrong.

**Comment by junkmd** [comment]
Thank you for bringing this to my attention.

I misunderstood the term of "universal wheels".
Upon your clarification, I checked and realized that the definition is documented at https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#wheels

Having removed the part that I misunderstood, and what I essentially wanted to tell is "It is **a wheel available package** if it has **one or more `.whl` files** in the Built Distribution section of `https://pypi.org/project/NAME/#files`".

Thank you.
