### ISSUE TITLE
Typo in safearray_as_ndarray conversion to numpy for _get_elements_raw()?

### ISSUE THREAD

**Issue by bennyrowland** [enthought/comtypes#238]
In the below line which is part of unpacking a safearray into (perhaps) an ndarray, the mapping of ctypes types to numpy dtypes is checked to see if the type of the safearray is supported by numpy, so that a direct conversion of the data is possible. However, it checks the values() which as far as I can tell are the numpy dtypes, surely it should be checking the keys() instead?

https://github.com/enthought/comtypes/blob/8f3abc93c213fccdf9cae54aa88bfc1dfc17b8e9/comtypes/safearray.py#L311

**Comment by cfarrow** [comment]
The `typecodes` keys are strings that map to ctype types (such as `c_byte`, `c_double`, etc.). The `_itemtype_` class attribute for the comtypes adapters is also a ctype type (not an instance), thus the lookup via values is correct.

Have you encountered a specific issue in this area of the code?

**Comment by bennyrowland** [comment]
@cfarrow where the typecodes dictionary is created in npsupport.py (lines 81 to 98 or so) there is an intermediate variable called ctypes_to_dtypes which is assigned to ctypeslib._typecodes. When doing some debugging of this feature I stepped through the `_get_elements_raw()` code (being called as part of a COM function returning a safearray of floats) and `typecodes` certainly seemed to be a mapping from ctypes to dtypes rather than the other way around. Initially I found that my array was not converted to an ndarray, although this is masked by the fact that there is a subsequent conversion of the tuple to an ndarray in `unpack()`. Changing the line from values to keys changed the behaviour so that I now get an ndarray returned out of `_get_elements_raw()`, which I think avoids the element by element conversion into a tuple (signficant in my case with 8192 floats in the array).

**Comment by cfarrow** [comment]
In that case I believe the issue is in `npsupport.py`. On line 94, the key should be the numpy typecode and the value should be the ctypes type. This will produce an output of the same format as ` numpy.ctypeslib._typecodes`...

```
{'|i1': ctypes.c_byte,
 '<i2': ctypes.c_short,
 '<i4': ctypes.c_int,
 '<i8': ctypes.c_long,
 '|u1': ctypes.c_ubyte,
 '<u2': ctypes.c_ushort,
 '<u4': ctypes.c_uint,
 '<u8': ctypes.c_ulong,
 '<f4': ctypes.c_float,
 '<f8': ctypes.c_double}
```

That is what is expected inside of `_get_elements_raw`.

The `ImportError` branch on line 86 of `npsupport.py` may not be exercised by the tests. I'm not sure how to exercise that branch. What version of numpy are you using? Is there anything exceptional about the python version or environment?

**Comment by bennyrowland** [comment]
numpy 1.21.0, comtypes 1.1.10, Python 3.9, nothing else special. I have gone back to numpy 1.15 to find the _typecodes array and you are correct that there the dictionary is reversed, from ctype to dtype. It seems like the simplest solution is probably just to swap the keys and values when inserting into the dictionary on line 94. Note also that the current implementation gives the type classes rather than the string representations of those, also each to fix as np.dtype(tp).str.
I can put together a PR for this change if you like. I know that there is some desire to improve the automated testing, covering multiple versions of numpy is probably an important part of that, but not something I have a lot of experience with.

**Comment by cfarrow** [comment]
A PR would be great. What you propose looks right. Thank you. I don't have a working dev environment at the moment, but I'm happy to review.

**Comment by bennyrowland** [comment]
@cfarrow I have submitted a PR with the (minimal) change required (and accidentally a PR onto my own fork's master branch, sorry for the extra noise). I am afraid I couldn't figure out how to run the tests so have not added any additional tests to exercise this component, of course it also requires a recent version of numpy when running the test suites to hit this area. But it does solve my issue without making the change I originally proposed, which would have broken older versions of numpy. Let me know if I need to fix anything else to get it ready for merging.
