### ISSUE TITLE
Unable to Run Code because of error in_comobject.py

### ISSUE THREAD

**Issue by ComputerConnor** [enthought/comtypes#240]
tuple[Module("comtypes.COMError"), WindowsError]" is not valid exception class
Line 82 in _comoject.py
Have tried reinstall the module yet to no avail.
<img width="726" alt="git2" src="https://user-images.githubusercontent.com/56240039/137460134-24add952-8a98-415e-99f8-e0db060733c4.PNG">
<img width="753" alt="git3" src="https://user-images.githubusercontent.com/56240039/137460262-eaed93d3-9e76-4f34-a05d-0dbfba6b58ac.PNG">

**Comment by kdschlosser** [comment]
https://github.com/enthought/comtypes/releases/tag/1.1.11

**Comment by junkmd** [comment]
@ComputerConnor 
If the issue remains, please re-open.
