### ISSUE TITLE
Plz escalate: time stamping remains broken (ImportError: Typelib different than module)

### ISSUE THREAD

**Issue by fusentasticus** [enthought/comtypes#243]
Hi maintainers - could I gently ask you to weigh in on this issue? 

Several people have noticed that the comtypes client remain broken in common use cases -- this is due to a timestamp mechanism that should ensure that wrappers are freshly generated when the typelib changes.  See complaints and ideas from the last few months here:

https://github.com/enthought/comtypes/issues/231
https://github.com/enthought/comtypes/issues/231#issuecomment-955571421
https://github.com/enthought/comtypes/pull/237

I have submitted an attempt at understanding and fixing this problem for good, please see https://github.com/enthought/comtypes/pull/241

But I haven't tested it much and it's clear that several sets of eyes are needed to get this right! Hope this will help!

**Comment by kdschlosser** [comment]
give this one a try. 

https://github.com/enthought/comtypes/pull/275

It is a modified version of the fix you have done. This one covers a broader range of timestamp related issues.
Once we know it is working as it should be the PR will get merged.

**Comment by junkmd** [comment]
@vasily-v-ryabov 
I think the problem reported in this issue has been resolved in 1.1.13.
I think this issue should be closed.

**Comment by vasily-v-ryabov** [comment]
@fusentasticus if the issue remains, please re-open.
