### ISSUE TITLE
error of lib itself

### ISSUE THREAD

**Issue by adiee5** [enthought/comtypes#246]
when i run script itself it says:
```  
File "D:\disSzczur\srakammmm\lib\site-packages\comtypes\__init__.py", line 1020, in <module>
    class helpstring(unicode):
NameError: name 'unicode' is not defined
```
could someone help?

**Comment by YoungMan3281** [comment]
Got the same issue~ I'm using python 3.9 
```
  File "C:\python39\lib\site-packages\comtypes\__init__.py", line 1020, in <module>
    class helpstring(unicode):
NameError: name 'unicode' is not defined
```

**Comment by junkmd** [comment]
@adiee5 
@YoungMan3281 

[`comtypes==1.1.11`](https://github.com/enthought/comtypes/releases/tag/1.1.11) has been added the bridge for resolve them.

https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/__init__.py#L98-L101
If the issue remains, please re-open.
