### ISSUE TITLE
IndexError for zero length SafeArrays

### ISSUE THREAD

**Issue by BALOGHBence** [enthought/comtypes#247]
The unpack function in safearray.py throws an error for SafeArrays of zero length.

https://github.com/enthought/comtypes/blob/master/comtypes/safearray.py#:~:text=return%20ub%20%2D%20lb-,def%20unpack(self)%3A,-%22%22%22Unpack%20a%20POINTER

Returning an empty tuple for the case dim==0 solves the issue

**Comment by vasily-v-ryabov** [comment]
Fix is moved to PR #259.
