### ISSUE TITLE
'''NameError: name 'unicode' is not defined''' on Python 3.10.0

### ISSUE THREAD

**Issue by water5** [enthought/comtypes#255]
On Python 3.10.0, 
```python
import comtypes
```

> Traceback (most recent call last):
>   File "\<stdin\>", line 1, in '\<module\>'
>   File "C:\Program Files\Python310\lib\site-packages\comtypes\\\_\_init\_\_.py", line 1020, in '\<module\>'
>     class helpstring(unicode):
> NameError: name 'unicode' is not defined

On Python 3.9.7 have not this issue.

**Comment by kdschlosser** [comment]
here are 2 pull requests that fix the problem.

https://github.com/enthought/comtypes/pull/254
https://github.com/enthought/comtypes/pull/253

**Comment by kdschlosser** [comment]
https://github.com/enthought/comtypes/releases/tag/1.1.11
