### ISSUE TITLE
Syntax invalid    says   except COMError ,err

### ISSUE THREAD

**Issue by Abuhurerak** [enthought/comtypes#277]
In    __init__.py
 He says  line 375

Expect   COMError,err

**Comment by kdschlosser** [comment]
new release fixes this problem

https://github.com/enthought/comtypes/releases/tag/1.1.11

**Comment by vasily-v-ryabov** [comment]
`pip install -U comtypes`

**Comment by Abuhurerak** [comment]
Thank you for solve the problem

**Comment by Abuhurerak** [comment]
Hello,
I have one issue
Face_recognition not install
dlib  not install

It says
running setup.py install for dlib did not run successfully.

**Comment by vasily-v-ryabov** [comment]
@Abuhurerak how is it connected with `comtypes`? Do you have full error traceback that points to `comtypes`?

**Comment by Abuhurerak** [comment]
Yes, it is working.
I use
pip install -U comtypes
 Command

**Comment by vasily-v-ryabov** [comment]
Can we close the issue then?

**Comment by Abuhurerak** [comment]
Yes, you can do that.

**Comment by Abuhurerak** [comment]
Yes close the issue them
But one problem
For face_recognition not install it say
running setup.py install for dlib did not run successfully.
Can you help this issue

**Comment by vasily-v-ryabov** [comment]
Sorry, I don't know what is face_recognition. I can't be an admin of all projects on GitHub. :)

**Comment by Abuhurerak** [comment]
Thank you!
