### ISSUE TITLE
Minimum NumPy version?

### ISSUE THREAD

**Issue by cfarrow** [enthought/comtypes#33]
What should be the minimum supported NumPy version? NumPy is not required to use comtypes, but NumPy arrays can be converted to safearrays when encountered. Optionally, safearrays can be converted to NumPy arrays with the `safearray_as_ndarray` context manager.
#29 extends the use of NumPy arrays so that arrays of arbitrary objects can be converted to safearrays, provided those objects can be packed inside of a VARIANT. This enhancement requires NumPy 1.7, which suggests 1.7 as the minimum NumPy version.

**Comment by junkmd** [comment]
This is a very old issue.

The latest numpy discussion is in #333.

A new issue should be created to discuss which version of `numpy` to support.

@cfarrow
@rkern 
if the issue remains, please re-open.
