### ISSUE TITLE
Can I define interface manually?

### ISSUE THREAD

**Issue by the-vindicar** [enthought/comtypes#379]
I don't have a .tlb file for the COM interfaces I'm using (Media Foundation doesn't seem to have a singular tlb file and I don't have much luck tryibg to find the correct ones), but they are well documented.
Is there a way for me to manually define the needed interfaces that would be compatible with comtypes?
I can take a look at the autogenerated code to figure it out, but it does leave some questions. 
Such as: when defining \_methods\_, can I define only methods I want to use, or do I need to define every method?

**Comment by junkmd** [comment]
@the-vindicar

Do you know `VersionIndependentProgID`(like `"Excel.Application"` or `"Scripting.Dictionary"`) of the object you want?
If you know the ID, you can create the object by passing it to `comtypes.client.CreateObject`(the module defining the interface will be created at the same time).

For example, `IUnknown` and `IDispatch` are exactly "manually define"d interfaces.
They require `_methods_`(or `_disp_methods_`) and `_iid_`.

See this docstring.
https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/__init__.py#L803-L808

Setting the `_methods_` attribute to only the methods you want to use will not work unless they follow the `VTable order`.
And it is expected bad something happening if you don't cover all the methods that the object actually has.

**Comment by the-vindicar** [comment]
> Do you know `VersionIndependentProgID`(like `"Excel.Application"` or `"Scripting.Dictionary"`) of the object you want? If you know the ID, you can create the object by passing it to `comtypes.client.CreateObject`(the module defining the interface will be created at the same time).
It's less about *classes* and more about *interfaces*. I don't think interfaces have an alias like `VersionIndependentProgID`. I get the object reference, alright, but I get `IUnknown`. And I can't call `QueryInterface()` because I don't have a matching interface definition class. Documentation seems to state that `.tlb` files are the supposed way of getting interface definition classes, but I don't have those. Hence the question about how I can just define them myself instead of scouring the Web for the correct `tlb`s (and yes, I know there is a really good archive in the issues of this very repo).

> For example, IUnknown and IDispatch are exactly "manually define"d interfaces.
That's what I was looking at, though I wondered how much of those was "expected" of the iterface and how much was implementation details.

> Setting the `_methods_` attribute to only the methods you want to use will not work unless they follow the `VTable order`. And it is expected bad something happening if you don't cover all the methods that the object actually has.
Ahhha, that's what I wanted to know. Thanks.

**Comment by junkmd** [comment]
@the-vindicar 

I am glad I could help you.

If you plan your use case to the open source project, please let me know.
I have very recently become a collaborator of `comtypes`.
I intend to contribute this repository by learning about the various uses.
