### ISSUE TITLE
fix `typeinfo.LoadRegTypeLib` type annotation

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#380]
My priority has shifted to modifying other modules, so I hope someone else will finish this unfinished work.

## Currently
https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/typeinfo.py#L511-L516

## Suggested change
```py
def LoadRegTypeLib(guid, wMajorVerNum, wMinorVerNum, lcid=0):
    # type: (_UnionT[str, GUID], int, int, int) -> ITypeLib
    """Load a registered type library"""
    ...
```

## Ratiole
The constructor arg of `GUID` will be casted to `text_type`.
https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/GUID.py#L40-L42

And `str(GUID("xxxxxxxx-..."))` will return `'xxxxxxxx-...'`.
https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/GUID.py#L47-L53

Thus, there is no problem `guid` argument is either `str` or `GUID`.

**Comment by j0ker70** [comment]
can you assign this to me?
