### ISSUE TITLE
There is a strange, perhaps unnecessary space in `typeinfo.IRecordInfo._methods_`

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#381]
Can someone please fix it?

https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/typeinfo.py#L442

**Comment by j0ker70** [comment]
Can you assign it to me?

**Comment by junkmd** [comment]
@j0ker70 

OK, I'll leave it for you.
