### ISSUE TITLE
fix `CoCreateInstance` type annotation

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#386]
`CoCreateInstanceEx` is annotated with a return value based on the type variable passed as an argument.

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/comtypes/__init__.py#L1095-L1099

However, `CoCreateInstance` does not.

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/comtypes/__init__.py#L919-L922

Please fix as follows.
```py
    @overload
    def CoCreateInstance(clsid, interface, clsctx=None, punkouter=None):
        # type: (GUID, Type[_T_IUnknown], Optional[int], Optional[pUnkOuter]) -> _T_IUnknown
        pass
```

**Comment by junkmd** [comment]
The type hinting related enhancements related to #327 are moving toward inline annotations(not comments), and it is planned to develop on a branch that is based on Python3-only support.

I will assign this issue to myself to work on this to prevent a new branch from being created from `master` with the wrong annotation.

**Comment by kdschlosser** [comment]
I believe that all COM interfaces have IUnknown as a base class. So if you are type hinting the return value type hint it as IUnknown.

**Comment by junkmd** [comment]
`_T_IUnknown` is the `IUnknown`-bound type variable.

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/comtypes/__init__.py#L780

And this ["serve as the parameters for generic function definitions"](https://docs.python.org/3/library/typing.html#typing.TypeVar).

```py
# they are examples of the type analyzer behavior. In runtime, they are not available.
a = CoCreateInstance(GUID(), IUnknown)  # `a` is recognized as `IUnknown` instance by type analyzer.
b = CoCreateInstance(GUID(), IPersist)  # `b` is recognized as `IPersist` instance by type analyzer.
c = CoCreateInstance(GUID(), IServiceProvider)  # `c` is recognized as `IServiceProvider` instance by type analyzer.
```
