### ISSUE TITLE
update `README.md`

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#399]
The `README.md`, that appears in [the GitHub repository page](https://github.com/enthought/comtypes#readme) and in [the PyPI project page](https://pypi.org/project/comtypes/), contains outdated content that can be confusing to newcomers.

- Is "Mailing list" alive?
  - I think platform for the community interaction should be unified with GitHub issue tracker.
  - If necessary, GitHub discussions could be adopted.
- The supported Python versions are not written.
  - [`.svg` badge](https://badge.fury.io/for/py) looks great!
- The writing style is old.
  - making effective use of markdown notation.
- "in less than 10000 lines of code" is no longer.
  - But adding "(excluding tests and blank lines)", then falling within that range.
- etc...

We must also mention the removal of Python2 support, which is addressed in #392.

Any opinions would be appreciated.

**Comment by junkmd** [comment]
As I watched PEP8 being applied in #403, I wondered something.

In modern programming, as a well-known fact, fewer lines of code does not directly related to readability.
So "in less than xxx lines of code" might not be attractive.
Instead, it may discourage the implementation of new features and more fixing bugs.

**Comment by junkmd** [comment]
@vasily-v-ryabov 

The badge displaying the PyPI version is rendered as follows:
[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/comtypes)](https://pypi.org/project/comtypes/)

I think it is necessary to set which 3.x is supported.

**Comment by vasily-v-ryabov** [comment]
Agree, we can set Py2.7 and Py3.7+ version in PyPI metadata (`setup.py`) similar to pywinauto's `setup.py`.

**Comment by vasily-v-ryabov** [comment]
This badge seems to read the metadata from PyPI.

**Comment by junkmd** [comment]
#404 and #460 are merged.
