### ISSUE TITLE
FAIL in test_LoadTypeLibEx

### ISSUE THREAD

**Issue by cfarrow** [enthought/comtypes#40]
Seen in the x86 tests for #32. The failure is not related to that PR.

``` python
======================================================================
FAIL: test_LoadTypeLibEx (comtypes.test.test_typeinfo.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build\lib\comtypes\test\test_typeinfo.py", line 34, in test_LoadTypeLibEx
    self.failUnlessEqual(tlib, other_tlib)
AssertionError: <POINTER(ITypeLib) ptr=0x69f3a8 at 2600a30> != <POINTER(ITypeLib) ptr=0x69f7f8 at 709b8f0>

----------------------------------------------------------------------
```

**Comment by junkmd** [comment]
@cfarrow 
I thought this test may be depended on environments.

I interpreted this is resolved by #298 and https://github.com/enthought/comtypes/pull/295#issuecomment-1148737128

Current test code is following
https://github.com/enthought/comtypes/blob/30523b53fbd5560d5bde2e722607c860cdf743dd/comtypes/test/test_typeinfo.py#L24-L39

if the issue remains, please re-open.
