### ISSUE TITLE
Convert Decimal to VT_DECIMAL instead of VT_CY?

### ISSUE THREAD

**Issue by cfarrow** [enthought/comtypes#42]
Currently Decimal objects are converted to currency variants (VT_CY) when passed as a VARIANT argument. However, there is a decimal VARIANT (http://msdn.microsoft.com/en-us/library/cc234586.aspx), which seems like the less surprising conversion choice. I can think of some practical reasons for converting Decimals to currency, but those reasons are not universal and should probably not define the default conversion behavior.

Right now I see no reason to change this, except that it "feels wrong". Any other opinions?

**Comment by junkmd** [comment]
I believe this was resolved in #44.
