### ISSUE TITLE
drop_py2 semanting versioning: Go for version 2.0.0 instead of 1.3.0?

### ISSUE THREAD

**Issue by jonschz** [enthought/comtypes#503]
Even though the drop_py2 project only breaks compatibility with Python 2, which has seen its EOL years ago, I would consider this to be a breaking change. By semanting versioning best practices, we should increase the major version, not the minor version. See e.g. https://stackoverflow.com/q/56135768.

One practical reason is that most package managers update minor version bumps automatically but request manual confirmation to update major versions.

You might have considered this already and may very well have good reasons not to increase the major version - in that case, I'd be curious to learn the reasons for that.

**Comment by vasily-v-ryabov** [comment]
Terminology is floating a little bit. Sometimes `x.y.z` is `release.major.minor`, sometimes it is `major.minor.patch`. I have no personal preferences, though `2.0.0` should mean pretty big changes in my opinion.

**Comment by jonschz** [comment]
Just wanted to make sure it wasn't an oversight. I'm happy to close the ticket, maybe after @junkmd has voiced his opinion.

**Comment by junkmd** [comment]
I checked various packages to see whether digits to be incremented in the release when supporting Python2 ended were `x`, `y` or `z` out of `x.y.z`.

When they dropped support for Python2, `urllib3` was incrementing `x`, but `boto3` and `requests` were incrementing `y`. I searched for a while but could not find any packages that incremented `z`.

After all, I think it only depends on the culture of the package as to which (`x` or `y`) digit is incremented in such a release that ends support for a specific Python version.

**Comment by junkmd** [comment]
Let's look at past commits in terms of the magnitude of feature changes.

When we made backward-incompatible changes related to `numpy`, the `y` was incremented to `1.2.0` from `1.1.14`.

In light of that history of `comtypes`, I think that any changes that would make `comtypes` work only with Python 3 would be `1.3.0`.

I would like to keep `x` as it is now so that it can be incremented when there are more significant changes.

**Comment by jonschz** [comment]
sounds good! Just wanted to make sure this wasn't an oversight.
