### ISSUE TITLE
PyWinAuto installation fails on Python 3.12

### ISSUE THREAD

**Issue by manju1847** [enthought/comtypes#504]
Trying to install PyWinAuto on Python 3.12 environment. But I see errors during installation. I am able to install the same version of PyWinAuto on Python 3.8 and Python 3.10.

D:\softwares\Python12>python --version
Python 3.12.1

D:\softwares\Python12>pip list
Package  Version
-------- -------
comtypes 1.2.1
pip      23.2.1
pywin32  306
six      1.16.0

D:\softwares\Python12>pip install d:\softwares\PyWinAuto\pywinauto-atspi
Processing d:\softwares\pywinauto\pywinauto-atspi
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F765B5C8C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F764656810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F765D37350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F765D37680>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F765D378C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\softwares\Python12>

**Comment by manju1847** [comment]
My bad, submitted here instead of submitting in PyWinAuto. Hence closing this. Added this issue in PyWinAuto

**Comment by junkmd** [comment]
As a maintainer of `comtypes`, I am just interested to know whether you can do `pip install comtypes==1.2.1` in your environment.

If you can do that, and if the installation of packages such as `pywinauto`, etc. that have `comtypes` as a dependency fails, then the cause seems to be something other than `comtypes`.

**Comment by manju1847** [comment]
Yes. I am able to install comtypes 1.2.1. I think issue is something with PyWinAuto and Python 3.12. 

With same comtypes 1.2.1, I am able to install PyWinAuto with Python 3.10. 

As you said, issue is not with comtypes.
