### ISSUE TITLE
[Support] Get OSError: exception: access violation

### ISSUE THREAD

**Issue by moi15moi** [enthought/comtypes#521]
I am pretty sure it is a skill issue and comtypes may have nothing to do with my problem, but I can't find why I always get the exception ``OSError: exception: access violation writing 0x00007FFD2B0D4493`` when I run [~~this code~~](https://paste.pythondiscord.com/LM5Q). Link dead, use [code.zip](https://github.com/enthought/comtypes/files/14909322/LM5Q.zip)

```py
Traceback (most recent call last):
  File "file.py", line 182, in <module>
    test()
  File "file.py", line 174, in test
    font_set.GetMatchingFonts1(
OSError: exception: access violation writing 0x00007FFF33574493
```

Could someones help me understand why it happen? Do I assign the wrong type in my IDWriteFontSet class?

**Comment by junkmd** [comment]
Please include the traceback output when an error occurs. 
Knowing which line the error occurred on is important for the community to assist with bug resolution.

In COM object method definitions, it is necessary to specify the Vtbl layout.

https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733

The order of method definitions is crucial, I believe.

**Comment by moi15moi** [comment]
> Please include the traceback output when an error occurs.

I edited my first message.

> The order of method definitions is crucial, I believe.

Yes, it is. I respected the order defined by the [header](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/dwrite_3.h#L507-L684).

**Comment by junkmd** [comment]
`IDWriteFontSet.GetPropertyValues` is duplicated in three places.
Not implementing this section may be causing inconsistencies in the vtbl index.

**Comment by moi15moi** [comment]
There are multiple place here where i don't specify the parameters here it and it works: https://github.com/moi15moi/FindSystemFontsFilename/blob/main/find_system_fonts_filename/windows_fonts.py

I think the issue is something else.

**Comment by junkmd** [comment]
While reading the [`IDWriteFontSet`](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritefontset) documentation, I noticed that `GetPropertyValues` and `GetMatchingFonts` are declared as overloaded methods.

Furthermore, regarding the relationship between overloaded methods and COM visible interfaces, Microsoft's documentation mentions the following.

https://learn.microsoft.com/en-us/visualstudio/code-quality/ca1402?view=vs-2019&tabs=csharp

> When overloaded methods are exposed to COM clients, only the first method overload retains its name. Subsequent overloads are uniquely renamed by appending to the name an underscore character '_' and an integer that corresponds to the order of declaration of the overload.

I'm not sure how much of that description is also common to Python and `comtypes`. However, I think trying out the following code changes is a low-cost way.

```diff
IDWriteFontSet._methods_ = [
    STDMETHOD(wintypes.UINT, "GetFontCount"),
    STDMETHOD(HRESULT, "GetFontFaceReference", [wintypes.UINT, POINTER(POINTER(IDWriteFontFaceReference))]),
    STDMETHOD(None, "FindFontFaceReference"),  # Need to be implemented
    STDMETHOD(None, "FindFontFace"),  # Need to be implemented
    STDMETHOD(None, "GetPropertyValues"),  # Need to be implemented
-   STDMETHOD(None, "GetPropertyValues"),  # Need to be implemented
+   STDMETHOD(None, "GetPropertyValues_2"),  # Need to be implemented
-   STDMETHOD(None, "GetPropertyValues"),  # Need to be implemented
+   STDMETHOD(None, "GetPropertyValues_3"),  # Need to be implemented
    STDMETHOD(None, "GetPropertyOccurrenceCount"),  # Need to be implemented
-   STDMETHOD(HRESULT, "GetMatchingFonts1", [POINTER(DWRITE_FONT_PROPERTY), wintypes.UINT, POINTER(POINTER(IDWriteFontSet))]),
+   STDMETHOD(HRESULT, "GetMatchingFonts", [POINTER(DWRITE_FONT_PROPERTY), wintypes.UINT, POINTER(POINTER(IDWriteFontSet))]),
-   STDMETHOD(HRESULT, "GetMatchingFonts2", [POINTER(wintypes.WCHAR), wintypes.UINT, wintypes.UINT, wintypes.UINT, POINTER(POINTER(IDWriteFontSet))]),
+   STDMETHOD(HRESULT, "GetMatchingFonts_2", [POINTER(wintypes.WCHAR), wintypes.UINT, wintypes.UINT, wintypes.UINT, POINTER(POINTER(IDWriteFontSet))]),
]
```

**Comment by junkmd** [comment]
Is there an update on this issue?

**Comment by moi15moi** [comment]
No. It still haven't found a solution.

**Comment by junkmd** [comment]
Does it mean that https://github.com/enthought/comtypes/issues/521#issuecomment-2002002584 did not provide a solution to the problem?

Even if it errors out, have you noticed any differences in the error message or error type compared to before?

**Comment by moi15moi** [comment]
No, it changes nothing. It give me the same error.
It doesn't surprise me. You can basically name the function like you want. I could rename ``GetFontCount`` to like ``example`` and call the method ``example`` and it would work.

**Comment by junkmd** [comment]
Is there an update on this issue?

Do you have any idea how to use `IDWriteFontSet` with languages other than Python or packages other than `comtypes`?
If those work as expected in your environment, I think it's worth investigating their implementation.

**Comment by moi15moi** [comment]
libass use it, but it is a pure C implementation, so it is a little bit different, but it gives you an idea.
It declare the interface [here](https://github.com/libass/libass/blob/2cea926568f0a06c2ec38b30bfb83714a6e259f1/libass/dwrite_c.h#L771-L815).
It call IDWriteFontSet::GetMatchingFonts [here](https://github.com/libass/libass/blob/2cea926568f0a06c2ec38b30bfb83714a6e259f1/libass/ass_directwrite.c#L946-L947).

**Comment by moi15moi** [comment]
I found the issue, like I said, it was a skill issue. Here is the new code: [LM5Q.zip](https://github.com/enthought/comtypes/files/15042211/LM5Q.zip)

I needed to switch the 2 ``GetMatchingFonts`` method in IDWriteFontSet. The new order doesn't follows the [header](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/dwrite_3.h#L507-L684) file, so I don't know why I needed to do that.

**Comment by junkmd** [comment]
I’m glad to hear that the issue seems to be resolved.

The [header file](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/dwrite_3.h#L507-L684) you were referring to hasn’t been updated for 9 years.
Probably, this difference in the vtable order is a discrepancy between the current and past specifications, which is inherent in software development.

Also, for the first time, I considered how to implement the overloading of COM methods in `comtypes`.

Your report will likely serve as a reference to help the community when a similar situation arises.

Thank you.
