### ISSUE TITLE
Clarity of code snippet in docs

### ISSUE THREAD

**Issue by 8day** [enthought/comtypes#64]
It would be good if you clarified that GUIDs in [this snippet](1) should be completely different by alternating characters. E.g., instead of three _xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_ it'd be good to have _xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_, _yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy_ and _zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz_.

Of course, there's a sentence below the snippet that states that GUID must be unique ("separate"), but IMO it wouldn't hurt to clarify this in snippet itself.

**Comment by junkmd** [comment]
This should be discussed in #1 thread.
