### ISSUE TITLE
[Support] Windows Error 0xc0000002 Exception

### ISSUE THREAD

**Issue by moi15moi** [enthought/comtypes#644]
I am pretty sure it is a skill issue and comtypes may have nothing to do with my problem, but I can't find why I always get the exception.
```py
Traceback (most recent call last):
  File "C:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 426, in __del__
    self.Release()
  File "C:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 560, in Release
    return self.__com_Release()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -1073741822] Windows Error 0xc0000002
```

From what I can see in the [Microsoft documentation](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55), ``0xc0000002`` is ``STATUS_NOT_IMPLEMENTED``. I don't really understand why it happens.

It occurs when I run this code with this [PR](https://github.com/moi15moi/FindSystemFontsFilename/pull/24/files) (due to the high dependency across various parts of the code, creating a small, self-contained example is quite difficult):
```py
from find_system_fonts_filename import get_font_fallback
get_font_fallback("Arial", 700, False, "😁")
```
If I add a ``print(self)`` [here](https://github.com/enthought/comtypes/blob/4cbdb03b31583c6a974dd690d38f1abe69767dda/comtypes/_post_coinit/unknwn.py#L559), it prints me ``<POINTER(IDWriteFont) ptr=0x2949ed64a50 at 2949e84c5d0>``.
I'm wondering if it happens because [here](https://github.com/moi15moi/FindSystemFontsFilename/blob/528329a2e71c0907dcba385bdd41e53c79245ef2/find_system_fonts_filename/windows/windows_fonts.py#L329), I pass a pointer of my IDWriteFont that I use [here](https://github.com/moi15moi/FindSystemFontsFilename/blob/528329a2e71c0907dcba385bdd41e53c79245ef2/find_system_fonts_filename/windows/windows_fonts.py#L453).

Do you have any idea what I could do wrong?

### My environment
**Python version**: 3.11.7
**comtypes version**: 1.4.8

**Comment by junkmd** [comment]
I believe this issue is due to the behavior of `IDWriteFont`. Since I am not very familiar with this interface, I can't provide quick and accurate advice, but I would like to assist in resolving the issue.

If we can solve this problem, it could serve as a useful reference for troubleshooting when manually defining custom interfaces using `comtypes` in the future.

I noticed that the program flow does not proceed after the `HasCharacter` call. What happens if you don't call `HasCharacter` or call a different method instead?

I'm not entirely sure why the error occurs when `Release` is called. It’s unclear whether the issue stems from incorrect parameter specifications for the COM methods as seen in https://github.com/enthought/comtypes/issues/521 and https://github.com/enthought/comtypes/issues/607, or if it's caused by something entirely different.

**Comment by moi15moi** [comment]
> What happens if you don't call `HasCharacter` or call a different method instead?

It doesn't seems that ``HasCharacter`` is the problem because I added some print and a call of ``GetInformationalStrings`` in this [commit](https://github.com/moi15moi/FindSystemFontsFilename/pull/24/commits/9c48472df248922ef2702779329d4a98b022ffec) and now the output is:
```py
2b780b<POINTER(IDWriteFont) ptr=0x1d594494840 at 1d594344950>
This print is displayed
Before HasCharacter
After HasCharacter
Exception ignored in: <function _compointer_base.__del__ at 0x000001D592A854E0>
Traceback (most recent call last):
  File "C:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 386, in __del__   
    self.Release()
  File "C:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 534, in Release   
    return self.__com_Release()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -1073741822] Windows Error 0xc0000002
```

**Comment by moi15moi** [comment]
I fixed the bug in this [commit](https://github.com/moi15moi/FindSystemFontsFilename/pull/24/commits/e7fa0567c9e4400853d2337c11a1c0ef75f848bb). I am surprised that I could call `font.HasCharacter` even when the font wasn’t properly instantiated with `font_collection.GetFontFromFontFace(fontFace, font_ptr[0])`. The issue arose from not creating the font object correctly. 

Now, I ensure the font is properly initialized by calling `font_collection.GetFontFromFontFace(fontFace, font_ptr)`. This guarantees that the font is correctly instantiated before invoking `HasCharacter`. Now, the code behaves as expected.
