### ISSUE TITLE
python comtypes how to pass numpy float32 (singe-precision float) as scalar?

### ISSUE THREAD

**Issue by denfromufa** [enthought/comtypes#86]
http://stackoverflow.com/questions/32617904/python-comtypes-how-to-pass-numpy-float32-singe-precision-float-as-scalar

```
According to comtypes documentation is is possible to pass numpy arrays to comtypes objects, but how to I pass scalar values, e.g. numpy.float32(1.0)?

https://pythonhosted.org/comtypes/#numpy-interop

I get following error:

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-67-9e7e5859c6a5> in <module>()
----> 1 com_obj.Update("string_name",np.float32(6.6e-6))
ArgumentError: argument 2: <type 'exceptions.TypeError'>: Cannot put 6.5999998e-06 in VARIANT
```

**Comment by cfarrow** [comment]
It is possible to add support for this, but I believe the fastest solution would be to pass a `ctypes.c_float`.

**Comment by denfromufa** [comment]
that worked perfectly! thanks @cfarrow, please post your answer on stackoverflow, if you have an account.

How can I convert to VT_BSTR and VT_BOOL?

does ctypes support all of these types in this link below? 

https://msdn.microsoft.com/en-us/library/ms256088(v=vs.110).aspx

**Comment by cfarrow** [comment]
Ctypes does not, but the `VARIANT` struct in `comtypes.automation` does.

**Comment by junkmd** [comment]
@denfromufa 
@cfarrow 

The problem seems to be resolved, so I close this.
if the issue remains, please re-open.
