### ISSUE TITLE
comtypes 1.1.2 installation error on ActivePython 2.7.8.10 x64 (Win8.1 x64)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [enthought/comtypes#99]
When I downloaded comtypes 1.1.2 and ran `python setup.py install` it outputs the following at the end:

```
Processing comtypes-1.1.2-py2.7.egg
creating c:\python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg
Extracting comtypes-1.1.2-py2.7.egg to c:\python27_x64\lib\site-packages
  File "c:\python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg\comtypes\__in
it__.py", line 902
    class _compointer_base(c_void_p, metaclass=_compointer_meta):
                                              ^
SyntaxError: invalid syntax

  File "c:\python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg\comtypes\test
\test_variant.py", line 304
    print("%40s: %7.1f us" % (msg, duration), file=sys.stderr)
                                                  ^
SyntaxError: invalid syntax

  File "c:\python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg\comtypes\test
\__init__.py", line 95
    print("Skipped %s: %s" % (modname, detail), file=sys.stderr)
                                                    ^
SyntaxError: invalid syntax

  File "c:\python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg\comtypes\tool
s\codegenerator.py", line 172
    print("from %s import %s" % (mod, name), file=self.imports)
                                                 ^
SyntaxError: invalid syntax

Adding comtypes 1.1.2 to easy-install.pth file
```

After importing comtypes I have another error:

```
Traceback (most recent call last):
  File ".\pywinauto\unittests\test_UIAWrapper.py", line 10, in <module>
    from pywinauto.application import Application
  File ".\pywinauto\__init__.py", line 30, in <module>
    from . import findwindows
  File ".\pywinauto\findwindows.py", line 32, in <module>
    from . import win32functions
  File ".\pywinauto\win32functions.py", line 24, in <module>
    from . import win32defines, win32structures
  File ".\pywinauto\win32structures.py", line 28, in <module>
    from . import sysinfo
  File ".\pywinauto\sysinfo.py", line 26, in <module>
    import comtypes
  File "C:\Python27_x64\lib\site-packages\comtypes-1.1.2-py2.7.egg\comtypes\__init__.py", line 902
    class _compointer_base(c_void_p, metaclass=_compointer_meta):
                                              ^
SyntaxError: invalid syntax
```

P.S. On Win7 x64 it works fine.

**Comment by vasily-v-ryabov** [comment]
This issue is reproduced after I installed `comtypes` on Python 3.4 64-bit and then ran `python setup.py install` for Python 2.7 64-bit.

When I unpacked sources from scratch, I've installed it successfully. But issue #98 is reproduced anyway.

Many other packages allow installing into many Pythons without special clean-up. I'd prefer not thinking how many times I've run `setup.py install` and for which Pythons.

**Comment by vasily-v-ryabov** [comment]
It's interesting. To maintian Py2/Py3 compatibility comtypes uses 2to3 fixer on the fly while running `setup.py`. Generally it works but some inconveniences are here. For example, I cannot use `C:\Python34\python.exe setup.py test` because 2to3 fixers are not running in this case. So potential contributors who mostly work on Py3 need some additional steps to run unit tests.

What do you think about Continuous Integration set up for the project? AppVeyor is a great CI service working on Windows. I see you've tried with Wine on Travis-CI. It's also interesting (didn't know about this approach), but AppVeyor is also great additional (and native) option.

**Comment by cfarrow** [comment]
I tried wine + Travis without success. I also hear that AppVeyor is great. It's on my todo list to set this up, as well as to update the tests so they can be run cleanly with `python -m unittest` or `nosetests`. (I would like to see `python setup.py test` go away.)

**Comment by junkmd** [comment]
[`comtypes==1.1.11`](https://github.com/enthought/comtypes/releases/tag/1.1.11) has been added the bridge to resolve them.

And AppVeyor CI is working currently.

If the issue remains, please re-open.
